image:
  repository: ghcr.io/firestartorg/firekit-example
  pullPolicy: Always
  tag: main

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

service:
  type: ClusterIP
  port: 3000
